version: '3'
services:
  idp:
    image: jboss/keycloak:12.0.4
    ports:
      - "7443:8443"
      - "7070:8080"
      - "7770:9990"
    environment:
      KEYCLOAK_USER: bruce
      KEYCLOAK_PASSWORD: i<3bats
      DB_VENDOR: postgres
      DB_ADDR: scrambled_keycloak_db
      DB_USER: keycloak
      DB_PASSWORD: keycloak
  scrambled_keycloak_db:
    image: library/postgres:13.1-alpine
    ports:
      - "7654:5432"
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
